# Copyright (c) 2020-2021 Carlo Masone

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or suholorantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.



# Project information
site_name: HolorLib
site_url: https://cmas1.io/HolorLib/
site_author: Carlo Masone
site_description: >-
  A C++ header-only library for generic multi-dimensional containers


# Repository
repo_name: cmas1/holorlib
repo_url: https://github.com/cmas1/HolorLib
edit_uri: ""


# Copyright
copyright: Copyright &copy; 2020 - 2021 Carlo Masone



# Configuration
theme:
  name: material
  custom_dir: docs/custom_home_theme


  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.instant
    #- navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.indexes
    - navigation.top
    # - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/holor_logo.png
  favicon: images/holor_logo.png

  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
      - Origin of the word Holor: getting_started/origin_of_holor.md
      - What's a Holor container: getting_started/holor_containers.md
  - Quickstart:
      - Installation: getting_started/install.md
      - Optional modules: getting_started/optional.md
  - Tutorials:
      - Layout basics: tutorials/layout.md
      - Holor basics: tutorials/holor.md
      - HolorRef basics: tutorials/holorref.md
      - Indexing a Holor or HolorRef container: tutorials/indexing.md
      - Slicing a Holor or HolorRef container: tutorials/slicing.md
      - Using Holor and HolorRef's iterators: tutorials/iterators.md


#Not editable
edit_uri: ""

#Extras
extra:
  version:
    provider: mike
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX


#to work with offline documentation
use_directory_urls: false


#Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.keys
  # - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 3
      permalink: true


#configuration and javascript for MathJax
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Plugins
plugins:
  - search
